# These sponsors are not yet configured.
# To add funding, link your GitHub Sponsors profile:
# https://github.com/sponsors

github: []
patreon: []
open_collective: []
ko_fi: []
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
otechie: []
lfx_crowdfunding: []
custom: []
